### ISSUE TITLE
Eliminate redundant and underused features

### ISSUE THREAD

**Issue by gk-brown** [gk-brown/MarkupKit#104]
MarkupKit has been in development for over 2 1/2 years now, and a number of features have been added that are either no longer needed or did not add as much value as initially expected. To keep the codebase manageable and reduce the learning curve for adoption, these features should be eliminated:

* `UIStackView` support - not necessary (overlaps with MarkupKit-provided layout views)
* `LMLayerView` - no longer necessary (overlaps with `LMAnchorView`)
* Includes and size class-specific layouts - can be accomplished via other more standard means such as custom view classes and child view controllers
* Font tables - does not provide significant value (system-defined text styles are generally sufficient)

**Comment by gk-brown** [comment]
That was my original thought, but then I realized that it probably wouldn't do much good. Since markup isn't compiled, any deprecated classes, properties, or methods wouldn't be flagged at build time.

In any case, deprecating a feature in an embedded framework like MarkupKit isn't as critical as it might be in a system framework. Unlike system updates, which are external to the app and thus out of our control, embedded frameworks are included with an app and generally don't need to be updated immediately.

I think the best option would be to provide a migration guide outlining what has changed, and what the suggested alternatives are.

**Comment by aceontech** [comment]
I totally agree these APIs should be removed, but I think people may be caught off guard if breaking changes occur in a minor release. I know I’d be kind of surprised if things stopped working simply by updating to 3.5.

**Comment by gk-brown** [comment]
I have historically bumped the minor version number when the only changes were the removal of minor features. However, in this case, a major version update may be justified. Do you think 4.0 would make more sense?

**Comment by gk-brown** [comment]
This is done.

**Comment by aceontech** [comment]
Yeah, I would suggest 4.0 too 👍🏽
