### ISSUE TITLE
How to remove  margin left and right 

### ISSUE THREAD

**Issue by prayuk545160** [gk-brown/MarkupKit#111]
![capture](https://user-images.githubusercontent.com/10814903/45264752-88894d00-b46b-11e8-9f9c-0f87904fef7d.JPG)

How to remove  margin left and right     in lmtableviewcell 
` <root>
<LMColumnView>
  <UIButton    style="systemButton" title=xxx" />
  <UIView  backgroundColor="#FFFFFF" height="1" />
</LMColumnView>
</root> 
`

**Comment by prayuk545160** [comment]
<root>
<LMColumnView>
  <UIButton    style="systemButton" title=xxx" />
  <UIView  backgroundColor="#FFFFFF" height="1" />
</LMColumnView>
</root>

**Comment by prayuk545160** [comment]
If you have a manual, it is very good.
I did not find it thanks

**Comment by gk-brown** [comment]
Have you tried the README?

https://github.com/gk-brown/MarkupKit/blob/master/README.md
