### ISSUE TITLE
I'm looking for a relative layout. Have an example? Try the LMLayerView and then have the error.

### ISSUE THREAD

**Issue by prayuk545160** [gk-brown/MarkupKit#112]
![relativelayout](https://user-images.githubusercontent.com/10814903/45275986-02601b80-b4ea-11e8-8c42-ec93cd5c8eb3.JPG)

I'm looking for a relative layout. Have an example? Try the LMLayerView and then have the error.

-> MarkupKit 4.5

**Comment by gk-brown** [comment]
`LMLayerView` no longer exists, but I think `LMAnchorView` may be what you are looking for:

https://github.com/gk-brown/MarkupKit/blob/master/README.md#lmanchorview
https://github.com/gk-brown/MarkupKit/wiki/Examples#anchor-view

**Comment by prayuk545160** [comment]
Thanks
