### ISSUE TITLE
Any plan for cocoapods & Swift version?

### ISSUE THREAD

**Issue by haducloc** [gk-brown/MarkupKit#2]
Thank you for awesome Lib. I am new to iOS. I am an Android developer. I found your lib is very similar to Android XML layout. I really hate Interface Builder & Storyboard & XIB xml layout. Why Apple did not do something like you are doing? Maybe because they are really smart? :)

Do you have a plan to put your lib into Cocoapods?

And any plan for Swift version?

Thank you!

**Comment by gk-brown** [comment]
Hi! Glad you find MarkupKit useful. I am also not a fan of IB and storyboards.  :-)

MarkupKit actually already works with Swift. In fact, all of the example code is written using Swift. Only the library itself is written in Objective-C. 

I don't currently have any plans to deploy MarkupKit via CocoaPods, but if there's enough interest it's certainly something I would be willing to look into.

Greg

**Comment by jakemarsh** [comment]
+1 for CocoaPods support. Would make it much easier to try out quickly. Check out their `pod try` command (http://blog.cocoapods.org/CocoaPods-0.29/) which would be great for seeing what MarkupKit is all about without needing to integrate it into my own project.

**Comment by gk-brown** [comment]
I added a Podspec for version 1.3.8. I tested it locally but it would be great if someone else could verify that it's working before I attempt to push it to the specs repo.

**Comment by gk-brown** [comment]
By the way, if you want to try it out without adding it to your own project, you can build and run the example target in the main project. It includes some basic examples of things you can do with MarkupKit.

**Comment by gk-brown** [comment]
I have pushed the Podspec for MarkupKit 1.3.8 to the Specs Repo. Let me know if you have any trouble accessing it.
