### ISSUE TITLE
adding RTL support

### ISSUE THREAD

**Issue by igor-makarov** [gk-brown/MarkupKit#59]
Hi,
Great framework. I'd really like to pilot its use here at Moovit, but it does not support right-to-left interfaces.

I was thinking of doing the changes myself and submitting them as a pull request, but I wanted to get your opinion on it first. How do you think would be best to handle it?

My proposition is:
1. Add respectLanguageDirection BOOL flag with default value=YES.
2. Switch to using Leading/Trailing instead of Left/Right in all the codebase when flag=YES and use Left/Right when flag is set to NO.

Cheers,
Igor

**Comment by gk-brown** [comment]
Interesting. Although I haven't tried it, RTL support should work (LMRowView already uses leading/trailing rather than right/left). Do you have an example I could use to test with?

**Comment by igor-makarov** [comment]
I'm sorry, you're correct. LMRowView is the only class that RTL behavior is relevant to and it's working properly according to my tests. 

I was having issues with `layoutMargins`. I'm beginning to understand that `layoutMargins` support in MarkupKit is merely a thin wrapper around UIKit's property, which isn't RTL compliant.

I assumed it to be something similar to XAML `margin` property.

Perhaps add full margin support? I'll start a new thread about it 😀
