### ISSUE TITLE
Allow markup documents to access values from Info.plist

### ISSUE THREAD

**Issue by gk-brown** [gk-brown/MarkupKit#68]
This feature would behave similarly to localized string resolution. A reserved prefix, such as "$", would be used to refer to values in the applications _Info.plist_ file. For example:

    <UILabel text="$CFBundleShortVersionString"/>

Custom values would be supported. Nested values could be accessed via KVC key paths.

**Comment by gk-brown** [comment]
This is done.

**Comment by gk-brown** [comment]
This change has been reverted. There isn't a strong use case for it, and the use of the "$" prefix would have precluded the use of string literals containing a leading "$" character.

**Comment by aceontech** [comment]
Couldn't we generalize this sort of thing and use markers like `{{` and `}}`?. A bit like all those JavaScript templating libraries (e.g. [Handlebars](http://handlebarsjs.com/) or similar).

**Comment by gk-brown** [comment]
I'm not sure the choice of delimiters matters that much. It's more that the information in _Info.plist_ is for system-level consumption. It's generally not user facing.

Also, MarkupKit already uses a leading "@" symbol for localization. So I'd be reluctant to adopt a different delimiter format for something similar.

I thought this feature might help me solve another problem I've been thinking about, but I think it's the wrong approach. I think I can actually solve it using the existing template property support.

**Comment by gk-brown** [comment]
FWIW, I actually support Mustache templates in my other project, [HTTP-RPC](https://github.com/gk-brown/HTTP-RPC).
