### ISSUE TITLE
Add support for conditional processing

### ISSUE THREAD

**Issue by gk-brown** [gk-brown/MarkupKit#75]
This would allow developers to selectively include or exclude blocks of content based on the current OS version. For example:

    <?if iOS?>
        ...
    <?else?>
        ...
    <?endif?>

or: 

    <?if tvOS?>
        ...
    <?else?>
        ...
    <?endif?>

**Comment by gk-brown** [comment]
Since the cases will only operate on a single value (the target OS) and will always be mutually exclusive, it may be simpler to implement this feature using the equivalent of a `switch` statement. For example:

    <?case iOS?>
        ...
    <?case tvOS?>
        ...
    <?end>

**Comment by aceontech** [comment]
+1 for `switch`

**Comment by gk-brown** [comment]
This is done.
