### ISSUE TITLE
Support loading views from alternate bundles

### ISSUE THREAD

**Issue by gk-brown** [gk-brown/MarkupKit#77]
This change would allow views to be loaded from external bundles (e.g. from a framework).

The `bundleForClass:` method of `NSBundle` would be used to identify the bundle of the view's owner. This bundle would be used in place of the main bundle in `viewWithName:owner:root:`. Static resources (i.e. property templates, images, strings, and font/color tables) would still be loaded from the main bundle.

**Comment by aceontech** [comment]
Referencing static resources like localization strings and images work fine. Haven't tried the other types specifically yet.

**Comment by gk-brown** [comment]
OK, thanks for confirming.

**Comment by gk-brown** [comment]
This is done.

**Comment by aceontech** [comment]
I ran into little a snag with regards the bundle loading feature. Short outline of the situation:

- `ViewController.swift` resides in a separate UI framework
- `ViewController.swift` renders its UI by loading `ViewController.xml`, also in the UI framework
- The main app depends on the UI framework
- The main app has a controller `SubclassedViewController.swift`, which is a subclass of `ViewController.swift`
- When `SubclassedViewController.swift` tries to load the xml declared in the UI framework, it fails to find it

LMViewBuilder.m line 121:

```objc
NSBundle *bundle = [NSBundle bundleForClass:[owner class]];
```

The bundle is determined by inspecting the current owner's class, but in this case, it's inspecting the subclass, which resides in the main app, and not the UI framework. Therefore the main app bundle is searched, instead of the UI framework.

I'm not quite sure how this can be solved using the current (automatic) approach.

My current workaround is to add the XML file to both the UI framework and the main app target. While this works, it's semantically incorrect and prone to error (i.e. forgetting to check the additional target box).

**Comment by gk-brown** [comment]
One option might be to add a method to the `Markup` category on `NSObject` that would allow the owner to customize the bundle to use for loading views. The default implementation could return `[NSBundle bundleForClass:[self class]]`, but subclasses could override it to return a different bundle.

**Comment by aceontech** [comment]
Ah yes, that may be an acceptable compromise. However, it still requires manual intervention, as in, remembering to override this method in case the class is open to subclassing.

**Comment by gk-brown** [comment]
True. But it still may be preferable to adding a bundle argument to the load method, since that could be confusing (not clear that the bundle applies only to view documents). The override approach could also be used to let the owner customize the bundle for loading strings and images as well (via different methods).

**Comment by gk-brown** [comment]
This is done. The following methods were added to `UIResponder` to facilitate bundle customization:

    - (NSBundle *)bundleForView;
    - (NSBundle *)bundleForStrings;

**Comment by aceontech** [comment]
Hi @gk-brown, I just got around to testing this and it works great. Thx.

**Comment by gk-brown** [comment]
Great - glad to hear it.

**Comment by aceontech** [comment]
You mentioned an override for image loading, is this implemented too?

**Comment by gk-brown** [comment]
No, that's not possible given the current implementation. Images are loaded by a method that doesn't have access to the owner (`applyMarkupPropertyValue:forKey` in `UIView`) so there's no way to ask the owner which bundle to use. Images, colors, and fonts are all still treated as "static" resources and need to live in the main bundle.

**Comment by aceontech** [comment]
Ah, right. Something to revisit at a later date then :-)

**Comment by gk-brown** [comment]
Possibly. If image handling was moved out of `applyMarkupPropertyValue:forKey:` (back into `LMViewBuilder`) then this could also be customizable. However, a few other things (fonts, colors, layout margins, etc.) are also decoded in the same method. I'm inclined to try to keep this logic together, so it might need to go back into `LMViewBuilder` as well. This seems OK, but I'd want to give it some thought first.

Font and color tables would need to remain static, since they are used by the `colorValue:` and `fontValue:` class methods in `LMViewBuilder`.

**Comment by aceontech** [comment]
One of my  `.xcassets` resides in a `.framework`; it would be nice if I could access those assets natively from markup. For now I'm using a simple `UIImage` subclass that loads images based on `imageName` from a specific bundle.

**Comment by aceontech** [comment]
But I agree, a change like this definitely needs more thought :)

**Comment by gk-brown** [comment]
I'm currently thinking that moving image, color, and font handling to `LMViewBuilder` would be OK and everything else could stay in `applyMarkupPropertyValue:forKey:`. Images would obviously have to move so the owner could be consulted for the image bundle. Color/font values are handled by the `colorValue:` and `fontValue:` methods of `LMViewBuilder`, so it seems natural to invoke those methods there. All of the other values are properties of `UIView` or its sub-types (layout margins, edge insets, etc.), so it also makes sense to leave that code where it is.

**Comment by gk-brown** [comment]
I added support for customizing the image bundle on the development branch. Would appreciate your feedback if you have a chance to check it out.

**Comment by aceontech** [comment]
Works: I removed my workaround. Good call on splitting the overrides up like that. It enables my situation, where the XML file sometimes resides in the main bundle, with the images and localization in a framework.

**Comment by gk-brown** [comment]
Excellent. I'll probably release 2.8.2 later today or tomorrow morning. Thanks for your help.
