### ISSUE TITLE
Add support for data binding

### ISSUE THREAD

**Issue by gk-brown** [gk-brown/MarkupKit#79]
This would facilitate development of [MVVM](https://en.wikipedia.org/wiki/Model–view–viewmodel)-style applications using MarkupKit. 

For example, instead of mapping a user interface element to an outlet and updating its state explicitly in the controller, a view could declare a binding to a "view model" object exposed by the controller:

    <UILabel text="$viewModel.text"/>

`viewModel` would refer to a property of the document's owner, and `text` to a property of the view model instance itself. Any time the value of the `text` property (or the `viewModel` property) changed, the label's text value would be automatically updated.

Change notifications would be handled via [key-value observing](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/KeyValueObserving/KeyValueObserving.html) (KVO).

**Comment by aceontech** [comment]
Awesome. Been thinking about this feature too!

**Comment by gk-brown** [comment]
Initial support for this feature has been added. However, it has not been fully tested or documented yet.

**Comment by gk-brown** [comment]
This is done.
