### ISSUE TITLE
Support or example for UITabBar

### ISSUE THREAD

**Issue by zachgrayio** [gk-brown/MarkupKit#84]
Sorry to keep opening issues! But I'm curious if UITabBar is supported, and if so, it'd be great to see some examples as i haven't had much luck with it so far.

**Comment by gk-brown** [comment]
I haven't attempted to support `UITabBar` since it seems like it is most commonly used in conjunction with `UITabBarController`. I'm curious to know what use cases there might be for creating tab bars outside of this context.

**Comment by gk-brown** [comment]
I prototyped this and I think it makes sense to implement. It's not done yet, but you can see the initial work on the development branch. I added a "Bars" example that will demonstrate how to work with both tool bars and tab bars in markup. Thanks for the suggestion!

**Comment by zachgrayio** [comment]
Awesome, can't wait to take a look.

**Comment by zachgrayio** [comment]
@gk-brown - looks pretty cool so far. Any idea on a timeframe for release yet?

**Comment by gk-brown** [comment]
Shouldn't be too long. I have a couple other things I'd like to get in, but they are relatively small.

**Comment by gk-brown** [comment]
This is done.
