### ISSUE TITLE
Best practices for supporting multiple screen sizes

### ISSUE THREAD

**Issue by zachgrayio** [gk-brown/MarkupKit#85]
I've laid out a few screens that look great on 4.7 and 5.5" screens, but they're not right on smaller screens as the font size doesn't autoscale, and the height, etc properties seem to all be in pixels rather than points.

Size Classes really don't offer enough control, and I'm curious what the best approach is to building a UI that supports multiple screen sizes.

**Comment by gk-brown** [comment]
Have you tried using `adjustsFontSizeToFitWidth`?

Width and height values should represent points (i.e. device-independent pixels). Not sure what might be going on there. But in general, you should try to avoid using hard-coded dimensions. View weights are a good way to dynamically adapt to different screen sizes and orientations.

Could you be a little more specific about how you are using size classes? Are you talking about UIKit's implementation in general or MarkupKit's support for them specifically?

**Comment by zachgrayio** [comment]
I'll give `adjustsFontSizeToFitWidth` and more use of weighted views a try - I had avoided both initially because we're implementing pixel-perfect designs and I wanted tight control over margins, font sizes but I'll give it a second look.

And yeah I just meant the general implementation. MarkupKit's support seems pretty solid.
