### ISSUE TITLE
LMTableView within an LMScrollView

### ISSUE THREAD

**Issue by zachgrayio** [gk-brown/MarkupKit#86]
Is this possible? Doesn't seem to render anything.

**Comment by gk-brown** [comment]
Definitely possible - you just need to make sure that you give the table view an explicit size (table views don't appear to calculate an intrinsic size):

<LMScrollView fitToWidth="true" backgroundColor="#eeeeee">
        <LMColumnView>
            <LMTableView height="240">
                <UITableViewCell textLabel.text="a"/>
                <UITableViewCell textLabel.text="b"/>
                <UITableViewCell textLabel.text="c"/>
                <UITableViewCell textLabel.text="d"/>
                <UITableViewCell textLabel.text="e"/>
                <UITableViewCell textLabel.text="f"/>
            </LMTableView>

            <LMTableView height="240">
                <UITableViewCell textLabel.text="a"/>
                <UITableViewCell textLabel.text="b"/>
                <UITableViewCell textLabel.text="c"/>
                <UITableViewCell textLabel.text="d"/>
                <UITableViewCell textLabel.text="e"/>
                <UITableViewCell textLabel.text="f"/>
            </LMTableView>

            <LMTableView height="240">
                <UITableViewCell textLabel.text="a"/>
                <UITableViewCell textLabel.text="b"/>
                <UITableViewCell textLabel.text="c"/>
                <UITableViewCell textLabel.text="d"/>
                <UITableViewCell textLabel.text="e"/>
                <UITableViewCell textLabel.text="f"/>
            </LMTableView>
        </LMColumnView>
    </LMScrollView>

**Comment by gk-brown** [comment]
Closing - assuming that this is resolved.
