### ISSUE TITLE
How to set padding  of uitableviewcell

### ISSUE THREAD

**Issue by prayuk545160** [gk-brown/MarkupKit#87]
if set  spacing="0" of first  LMColumnView  app will Error 
i wont to remove  space  of uitableviewcell

 <LMColumnView  layoutMargins="0"   >
 <LMColumnView layoutMargins="0" spacing="0"  >
     <UILabel  text=" " font="System 1" />
</LMColumnView>
</LMColumnView>

**Comment by prayuk545160** [comment]
<LMColumnView  layoutMargins="0"   >
 <LMColumnView layoutMargins="0" spacing="0"  >
   		<LMRowView>
		    <UIImageView restorationIdentifier="defimg"  image="p1.jpg" width="80" height="80" weight="1" />
			<LMColumnView>
			   <UILabel  text="Message"/>
			   <UILabel  text="yyyy" restorationIdentifier="openapp" />
			   <UILabel  text="  reply 12,like 12, comment 12 12/1/2017" textColor="#808080" />
			  <UIView />
			</LMColumnView>  
			
			<UIView />
		</LMRowView>
		<LMRowView  >
		     <UILabel  text=" " font="System 1" />
   		 </LMRowView>
</LMColumnView>
</LMColumnView>

**Comment by prayuk545160** [comment]
<LMColumnView  layoutMargins="0"   >
 <LMColumnView layoutMargins="0" spacing="0"  >
   		
		     <UILabel  text=" " font="System 1" />
</LMColumnView>
</LMColumnView>

**Comment by gk-brown** [comment]
Can you provide an example of the markup you are trying to use?

**Comment by prayuk545160** [comment]
<LMColumnView  backgroundColor="#ffffff">
<LMColumnView layoutMarginLeft="3"  layoutMarginRight="3"    spacing="0" >


<LMRowView  accessibilityLabel="cmd=rowtag;rowtag=$rowcmd;" spacing="3"   >
    <LMColumnView>
        <UIImageView    image="p1.jpg" height="60" width="60"
		 restorationIdentifier="defimg"   
		  />
    </LMColumnView>
		<LMColumnView   >
		  <UILabel  text="Notification"  />
		  <UILabel  text="openapp"  restorationIdentifier="openapp"  /> 
        </LMColumnView>
	</LMRowView>


</LMColumnView>
</LMColumnView>

**Comment by prayuk545160** [comment]
> <LMColumnView  backgroundColor="#ffffff">
> <LMColumnView layoutMarginLeft="3"  layoutMarginRight="3"    spacing="0" >
> 
> 
> <LMRowView  accessibilityLabel="cmd=rowtag;rowtag=$rowcmd;" spacing="3"   >
>     <LMColumnView>
>         <UIImageView    image="p1.jpg" height="60" width="60"
> 		 restorationIdentifier="defimg"   
> 		  />
>     </LMColumnView>
> 		<LMColumnView   >
> 		  <UILabel  text="Notification"  />
> 		  <UILabel  text="openapp"  restorationIdentifier="openapp"  /> 
>         </LMColumnView>
> 	</LMRowView>
> 
> 
> </LMColumnView>
> </LMColumnView>

**Comment by prayuk545160** [comment]
'<LMColumnView   layoutMarginsRelativeArrangement="false"  backgroundColor="#ffffff">
'<LMColumnView layoutMargins="0"   spacing="0" >

**Comment by prayuk545160** [comment]
```html
<LMColumnView  backgroundColor="#ffffff">
<LMColumnView layoutMarginLeft="3"  layoutMarginRight="3"    spacing="0" >


<LMRowView  accessibilityLabel="cmd=rowtag;rowtag=$rowcmd;" spacing="3"   >
    <LMColumnView>
        <UIImageView    image="p1.jpg" height="60" width="60"
		 restorationIdentifier="defimg"   
		  />
    </LMColumnView>
		<LMColumnView   >
		  <UILabel  text="Notification"  />
		  <UILabel  text="openapp"  restorationIdentifier="openapp"  /> 
        </LMColumnView>
	</LMRowView>


</LMColumnView>
</LMColumnView>
```

**Comment by gk-brown** [comment]
Can you please provide the complete markup for your cell? I assume you have a `<root>` tag in there somewhere?

**Comment by prayuk545160** [comment]
I created ui myself in tableviewcell.

**Comment by gk-brown** [comment]
I'm not sure what you mean by that. Could you please be more specific?

**Comment by prayuk545160** [comment]
```html
<UITableView>
<UITableViewCell>
<LMColumnView  layoutMargins="0"    >
 <LMColumnView layoutMargins="0" spacing="0"  >
   		<LMRowView>
		    <UIImageView restorationIdentifier="defimg"  image="p1.jpg" width="80" height="80" weight="1" />
			<LMColumnView>
			   <UILabel  text="Message"/>
			   <UILabel  text="yyyy" restorationIdentifier="openapp" />
			   <UILabel  text="  reply 12,like 12, comment 12 12/1/2017" textColor="#808080" />
			  <UIView />
			</LMColumnView>  
			
			<UIView />
		</LMRowView>
		<LMRowView  >
		     <UILabel  text=" " font="System 1" />
   		 </LMRowView>
</LMColumnView>
</LMColumnView>
</UITableViewCell>
</UITableView>

```

**Comment by gk-brown** [comment]
I see. In order to declare a table structure in MarkupKit, you need to use `LMTableView` and `LMTableViewCell`, not `UITableView` and `UITableViewCell`. The standard UIKit classes are not capable of hosting statically defined content. I'd suggest that you try that and see how it goes.

**Comment by prayuk545160** [comment]
I tried switching to LMTableView and LMTableViewCell and then rendering the same result. There is a space between the rows and then in each row. Try changing to <LMColumnView layoutMarginsRelativeArrangement = "true">

Experiencing fast But not sure if that is the recommended way?

**Comment by prayuk545160** [comment]
```html
 Try changing to
 <LMColumnView   layoutMarginsRelativeArrangement="true"  >
Experiencing fast But not sure if that is the recommended way?

```

**Comment by gk-brown** [comment]
Try setting `layoutMarginsRelativeArrangement="false"` on the `LMTableViewCell` element.

**Comment by prayuk545160** [comment]
Thank you very much for your help. Gk-brown
