### ISSUE TITLE
Live Preview

### ISSUE THREAD

**Issue by silentninja** [gk-brown/MarkupKit#89]
Thanks a lot for writing this library, it is way better than using storyboard or swift code. I am trying to get a live preview of the UI written in markupkit something similar to android studio layout editor. I tried using IBDesignable but I am getting the following error: 
```
file:///projpath/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ViewController (BYZ-38-t0r): The agent threw an exception.

file:///projpath/Main.storyboard: IB Designables: Failed to update auto layout status: The agent raised a "NSUnknownKeyException" exception: [<SampleApp.SampleView 0x7fb438f55d90> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key spacing.
```
The code i wrote is as follows:
*CustomView.xml*
```
<?xml version="1.0" encoding="UTF-8"?>

<LMColumnView topSpacing="32" bottomSpacing="32" spacing="64">
    <UIButton style="systemButton" title="Say Hello" onPrimaryActionTriggered="sayHello"/>
    <UILabel id="greetingLabel" font="headline" textAlignment="center"/>
    <LMSpacer/>
</LMColumnView>
```
SampleView.swift
```
import UIKit
import MarkupKit

@IBDesignable class SampleView: UIView {


    override func layoutSubviews() {
 LMViewBuilder.view(withName: "CustomView", owner: self, root: self)
    }
}

```

IBDesignable works for code written in swift though. 

If there are any other way to preview the layout without compiling, please do mention.

**Comment by gk-brown** [comment]
I haven't tried this myself, but it seems like it should be possible. When I get a chance, I'll see if I can get an example working.

In the meantime, I noticed a couple of issues with your example:

- Since you are passing your custom view instance as the root argument, you'll want to use a <root> tag in your markup.

- You may want load the markup in an initializer. Loading it in layoutSubviews() may cause it to be loaded multiple times. I'm also not sure how UIKit will handle modifications to the view hierarchy during layout.

**Comment by gk-brown** [comment]
Playgrounds might be another option. I wasn't able to get it to work, but maybe you will have better luck.  :-)

**Comment by silentninja** [comment]
By tag do you mean add an 'id' to it?

**Comment by silentninja** [comment]
I tried removing spacing key because that kvo error is occurring due to wrong key(same kvo error occurs for topSpacing and bottomSpacing too) so that the xml will be like 
```
<?xml version="1.0" encoding="UTF-8"?>

<LMColumnView>
    <UIButton style="systemButton" title="Say Hello" onPrimaryActionTriggered="sayHello"/>
    <UILabel id="greetingLabel" font="headline" textAlignment="center"/>
    <LMSpacer/>
</LMColumnView>
```

I got an kvo error for greetingLabel which i solved by adding
`@IBOutlet var greetingLabel: UILabel!`

Now it compiles without any error, but I am not able to see any content in the storyboard or in the compiled app.

I think the problem is occurring because no space constrains have been specified and if i use space constrains kvo error occurs as mentioned previously. Should I use something else instead of "spacing", "topSpacing" key?

**Comment by gk-brown** [comment]
Take a look at the section of the README that discusses the <root> element. Hopefully that will help clarify things.

**Comment by gk-brown** [comment]
Ah, I see. GitHub is stripping characters. See the section of the README that discusses the < root > element.

**Comment by gk-brown** [comment]
I just verified that this does actually work:

__CustomView.swift__

    import UIKit
    import MarkupKit

    @IBDesignable
    class CustomView: LMColumnView {
        override init(frame: CGRect) {
            super.init(frame: frame)

            LMViewBuilder.view(withName: "CustomView", owner: self, root: self)
        }

        required init?(coder decoder: NSCoder) {
            super.init(coder: decoder)

            LMViewBuilder.view(withName: "CustomView", owner: self, root: self)
        }

        deinit {
            unbindAll()
        }
    }

__CustomView.xml__

    <?xml version="1.0" encoding="UTF-8"?>

    <LMColumnView spacing="0" backgroundColor="white">
        <LMSpacer/>
        <UILabel text="Hello, World!" textColor="green" font="headline" textAlignment="center"/>
        <LMSpacer/>
    </LMColumnView>

I was able to modify values in __CustomView.xml__ and see them reflected in the storyboard editor. Updates don't always seem to happen automatically, though - sometimes it seems to be necessary to save the storyboard in order to see the changes.

**Comment by silentninja** [comment]
Thanks for the reference to elements section in README. I tried adding custom spacing property and it didn't throw up error instead nothing got rendered. Now i see the problem, you solution was spot on and it works great. Thanks for your support
